"""Initial migration - cleanup models

Revision ID: 6e6f8a7821cf
Revises: 
Create Date: 2025-12-05 10:39:01.976849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text


# revision identifiers, used by Alembic.
revision: str = '6e6f8a7821cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Sprawdza czy kolumna istnieje w tabeli"""
    bind = op.get_bind()
    inspector = inspect(bind)
    if not inspector.has_table(table_name):
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Usuń expires_at tylko jeśli istnieje
    if _column_exists('ammo', 'expires_at'):
        op.drop_column('ammo', 'expires_at')
    
    # Dodaj added_at tylko jeśli nie istnieje
    if not _column_exists('attachments', 'added_at'):
        op.add_column('attachments', sa.Column('added_at', sa.DateTime(), nullable=False))
    
    # Zmień typ kolumny type w attachments
    try:
        op.alter_column('attachments', 'type',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Enum('optic', 'light', 'laser', 'suppressor', 'bipod', 'compensator', 'grip', 'trigger', 'other', name='attachment_type_enum'),
                   existing_nullable=True)
    except Exception:
        pass  # Kolumna może już mieć poprawny typ
    
    if _column_exists('attachments', 'expires_at'):
        op.drop_column('attachments', 'expires_at')
    
    if _column_exists('attachments', 'image_path'):
        op.drop_column('attachments', 'image_path')
    
    # Usuń indeks tylko jeśli istnieje
    bind = op.get_bind()
    inspector = inspect(bind)
    if inspector.has_table('currency_rates'):
        indexes = [idx['name'] for idx in inspector.get_indexes('currency_rates')]
        if 'ix_currency_rates_date' in indexes:
            op.drop_index('ix_currency_rates_date', table_name='currency_rates')
    
    if _column_exists('guns', 'expires_at'):
        op.drop_column('guns', 'expires_at')
    
    op.alter_column('maintenance', 'rounds_since_last',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('maintenance', 'activities',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    
    if _column_exists('maintenance', 'rounds_fired'):
        op.drop_column('maintenance', 'rounds_fired')
    
    if _column_exists('maintenance', 'expires_at'):
        op.drop_column('maintenance', 'expires_at')
    
    if _column_exists('shooting_sessions', 'expires_at'):
        op.drop_column('shooting_sessions', 'expires_at')
    op.alter_column('user_settings', 'ai_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'off'"))
    op.alter_column('user_settings', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'dark'"))
    op.alter_column('user_settings', 'distance_unit',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'m'"))
    op.alter_column('user_settings', 'maintenance_rounds_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(500)'))
    op.alter_column('user_settings', 'maintenance_days_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(90)'))
    op.alter_column('user_settings', 'maintenance_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'low_ammo_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'ai_analysis_intensity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'normalna'"))
    op.alter_column('user_settings', 'ai_auto_comments',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'pl'"))
    op.alter_column('user_settings', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'pln'"))
    op.alter_column('users', 'skill_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'beginner'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'skill_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'beginner'"))
    op.alter_column('user_settings', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'pln'"))
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'pl'"))
    op.alter_column('user_settings', 'ai_auto_comments',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_settings', 'ai_analysis_intensity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'normalna'"))
    op.alter_column('user_settings', 'low_ammo_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'maintenance_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_settings', 'maintenance_days_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(90)'))
    op.alter_column('user_settings', 'maintenance_rounds_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(500)'))
    op.alter_column('user_settings', 'distance_unit',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'m'"))
    op.alter_column('user_settings', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'dark'"))
    op.alter_column('user_settings', 'ai_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'off'"))
    op.add_column('shooting_sessions', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.add_column('maintenance', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.add_column('maintenance', sa.Column('rounds_fired', sa.INTEGER(), nullable=True))
    op.alter_column('maintenance', 'activities',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('maintenance', 'rounds_since_last',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('guns', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.create_index('ix_currency_rates_date', 'currency_rates', ['date'], unique=False)
    op.add_column('attachments', sa.Column('image_path', sa.VARCHAR(length=500), nullable=True))
    op.add_column('attachments', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.alter_column('attachments', 'type',
               existing_type=sa.Enum('optic', 'light', 'laser', 'suppressor', 'bipod', 'compensator', 'grip', 'trigger', 'other', name='attachment_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('attachments', 'added_at')
    op.add_column('ammo', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###

